### ISSUE TITLE
update for dalamud 7.1

### ISSUE THREAD

**Issue by MKhayle** [NotNite/PizzaPlugin#1]
hllo can yuo add dominso piizza in dalamudno agani 
im hungry

**Comment by ArcaneDisgea** [comment]
witewy shaking pwease update pwogon befowe i die fwom stawvation

**Comment by NotNite** [comment]
IT NEVER EVEN WORKED IN THE FIRST PLACE

**Comment by MKhayle** [comment]
WHAT DO YOU MEAN IT DIDN'T WORK MAKE IT WORK

**Comment by Aida-Enna** [comment]
THEY DID GET IT TO WORK THEY JUST DON'T WANT TO SHARE THE CHEESY GOODNESS 😭
